name: Build and push the API container image

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/api.container.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

concurrency:
  group: "API Container"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          sparse-checkout: "api"
          sparse-checkout-cone-mode: false

      - name: Move files in the "api" folder to the root
        run: |
          ls -lah
          shopt -s dotglob
          mv api/* .
          rm -rf api
          ls -lah

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the docker image
        run: |
          docker build . --tag ghcr.io/${{ github.repository }}-api:latest
          docker push ghcr.io/${{ github.repository }}-api:latest